### PR TITLE
Fixes for v0.4, eltype dict is not a tuple

### PR DESCRIPTION
**Pull request by mdcfrancis**
Two small fixes to make URITemplate work on v0.4

### CODE REVIEW

**Comment by Keno** [comment]
I assume this should now make use of https://github.com/JuliaLang/julia/pull/12931. Also, since `keytype` is now exported, it might make sense to add the 0.3 definitions to `Compat`.

**Comment by mdcfrancis** [comment]
I don't believe the keytype and vatype were back ported into 0.4, I'll check though

**Comment by mdcfrancis** [comment]
Changed to using the exported version of keytype and also fixed up some of the type warnings.

**Comment by mdcfrancis** [comment]
Can this be merged in ?

**Comment by mdcfrancis** [comment]
Ping

**Comment by Keno** [comment]
Thanks!

**Pull request merged**
